apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: {{ .Values.deploymentName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: CHAOS_INTERVAL
              value: {{ .Values.chaos.interval | quote }}
            - name: CHAOS_STARTUP_DELAY
              value: {{ .Values.chaos.startupDelay | quote }}
            - name: MEMORY_CHUNK_SIZE
              value: {{ .Values.chaos.memoryChunkSize | quote }}
            - name: DISK_FILL_SIZE_MB
              value: {{ .Values.chaos.diskFillSizeMB | quote }}
            - name: CPU_BURN_THREADS
              value: {{ .Values.chaos.cpuBurnThreads | quote }}
            - name: CPU_BURN_DURATION
              value: {{ .Values.chaos.cpuBurnDuration | quote }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"  # Bei OOM_PRESSURE wird der Pod hier gekillt
              cpu: "200m"     # Bei CPU_SPIKE siehst du hier Throttling

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10 # Etwas mehr Puffer f√ºr den App-Start
            periodSeconds: 5
            timeoutSeconds: 2 
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2 
            failureThreshold: 3
          volumeMounts:
            - name: tmp-volume
              mountPath: {{ .Values.volume.mountPath }}
      volumes:
        - name: tmp-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}