image:
  repository: wlanboy/randomfail
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
deploymentName: randomfail

service:
  name: randomfail-svc
  type: ClusterIP
  port: 8080
  targetPort: 8080

pvc:
  enabled: true
  name: randomfail-tmp-pvc
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  size: "100Mi"

volume:
  mountPath: /tmp

chaos:
  interval: 300              # Sekunden zwischen Chaos-Zyklen
  startupDelay: 10           # Initialer Puffer beim Start
  memoryChunkSize: 1000000   # Bytes pro Memory-Chunk (1MB)
  diskFillSizeMB: 110        # MB f√ºr Disk-Fill
  cpuBurnThreads: 2          # Anzahl paralleler CPU-Threads
  cpuBurnDuration: 240       # Sekunden CPU-Burn Dauer

istio:
  gatewayName: randomfail-gw
  gatewayNamespace: "istio-ingress"
  hosts: 
    - randomfail.tp.lan
    - randomfail.gmk.lan
  tls:
    enabled: true
    secretName: randomfail-tls

certManager:
  enabled: true
  issuerRef:
    kind: ClusterIssuer
    name: "local-ca-issuer"
  dnsNames:
    - randomfail.tp.lan
    - randomfail.gmk.lan
